# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_mkdocs_tutorial',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/nbdev_mkdocs_tutorial',
                'lib_path': 'nbdev_mkdocs_tutorial'},
  'syms': {'nbdev_mkdocs_tutorial.core': {'nbdev_mkdocs_tutorial.core.foo': ('core.html#foo', 'nbdev_mkdocs_tutorial/core.py')}}}
